### ISSUE TITLE
gradle编译版本不一致

### ISSUE THREAD

**Issue by QDPeng** [leeowenowen/rxjava-examples#1]
compile 'io.reactivex:rxjava:1.0.10'
为什么编译后是rxjava1.1.8?
这样在CustomeOperatorActivity.class 找不到rx.internal.operators.OperatorMap这个类

**Comment by leeowenowen** [comment]
为了跟进rxjava api的变动，我把所有依赖的版本号都以+的方式配置在gradle中，但是犯了一个错，在自定义Operator的实现里，我扩展了原有的OperatorMap, 这样其实是依赖了RXJAVA的内部实现，这是不对的，理论上我之应当依赖其API  多谢提醒，已经修复。
